---
name: CI
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  ok:
    needs:
      - build-client
    if: failure()
    permissions: {}
    runs-on: ubuntu-24.04
    steps:
      - run: exit 1
  build-client:
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      pull-requests: write
    env:
      AQUA_CONFIG: ${{ github.workspace }}/aqua.yaml
      AQUA_POLICY_CONFIG: ${{ github.workspace }}/aqua-policy.yaml
      TZ: Asia/Tokyo
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: false
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: package.json
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342 # v4.0.3
        with:
          aqua_version: v2.55.1
      - continue-on-error: true
        run: |
          pnpm lint > out.txt
      - id: lint
        continue-on-error: true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: reviewdog -f eslint -fail-level any -filter-mode nofilter -reporter github-pr-review < out.txt
      - id: build
        run: pnpm build
        continue-on-error: true
      - if: ${{ steps.lint.outcome == 'failure' || steps.build.outcome == 'failure' }}
        run: exit 1
  test-server:
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        id: setup-go
        with:
          cache: true
          go-version-file: go.mod
      - run: go mod download
      - name: go test
        run: go test -coverpkg=./... -coverprofile=./coverage.out -timeout=30s ./backend/...
      - uses: k1LoW/octocov-action@73d561f65d59e66899ed5c87e4621a913b5d5c20 # v1.5.0
        with:
          version: v0.73.0
          config: octocov.backend.yml
